POST http://127.0.0.1:3000/auth/register
content-type: application/json

{
    "username": "sample222",
    "password": "lesgo",
    "skills":["hi","ji"]
}


###

DELETE http://127.0.0.1:3000/demo/delete/all
content-type: application/json



###


POST http://127.0.0.1:3000/video/get/explore
content-type: application/json

{
    "skill": "Hoe"
}



###

GET http://127.0.0.1:3000/video/explore/course/new?start=0&end=10