POST http://localhost:3000/demo/add
Content-Type: application/json

{
  "title":"14 new updatessdsdff in Threads",
  "blog":"Lorem ipsum dolor sitfsdfsdfdsf amet?"
}

###


DELETE http://localhost:3000/demo/delete/655e269a2473966fa5a2a038

###


GET http://localhost:3000/demo/blog/655e269a2473966fa5a2a038


###
PATCH  http://localhost:3000/demo/update/655e269a2473966fa5a2a038
Content-Type: application/json

{
  "title":"14 new  in Threads",
  "blog":"Lorem ipsum dolor sitfsdfsdfdsf amet?"
}